apiVersion: rbac.authorization.k8s.io/v1y
kind: ClusterRole
metadata:
  name: gitlab-runner-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]